---
title: "Data Visualization in R"
author: "Mehadi Hasan"
date: "2025-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# Install and load gapminder R Package
```{r}
#install.packages("gapminder")
library("gapminder")
```

# Execute the script to get the beautiful scatter plot
```{r}
gapminder_filtered <- gapminder |>
  filter(year == 2007)

ggplot(data = gapminder_filtered,
       mapping = aes(x = gdpPercap, y = lifeExp, 
                     size = pop, color = continent)) +
  geom_point() + 
  scale_x_log10(labels = scales::dollar_format(accuracy = 1)) +
  scale_size_continuous(labels = scales::label_comma()) +
  scale_color_viridis_d(option = "plasma") +
  labs(x = "GDP per capita", y = "Life expectancy",
       title = "Health and wealth are strongly related",
       subtitle = "142 countries; 2007 only", caption = "Source: The Gapminder Project",
       color = "Continent", size = "Population") +
  theme_bw()
```


# Plotting with tidyplots

```{r}
install.packages("tidyplots")

library("tidyplots")
```

